"""Normalized SQLite storage for Bilibili metadata.

The package root is the single import surface: the repository, the record
models, and the bootstrap helpers are all re-exported here.
"""

from bili_asr.storage.database import DatabaseConnection, SchemaContractError, duration_to_ms, initialize_schema, normalize_page_index, open_database, refresh_shipped_views, require_subtitle_schema
from bili_asr.storage.metadata import MetadataRepository
from bili_asr.storage.transcripts import TranscriptRepository
from .models import (
    ALLOWED_ACQUISITION_KINDS,
    ALLOWED_ACQUISITION_OUTCOMES,
    ALLOWED_ATTEMPT_OUTCOMES,
    ALLOWED_CAPTION_SOURCE_KINDS,
    ALLOWED_CURSOR_STATES,
    ALLOWED_LOCAL_TRANSCRIPT_SOURCE_KINDS,
    ALLOWED_PAGE_OUTCOMES,
    ALLOWED_PROCESSING_STATUS,
    ALLOWED_RUN_OUTCOMES,
    ALLOWED_SOURCE_KINDS,
    MAX_TIMELINE_MS,
    AcquisitionKind,
    AcquisitionOutcome,
    AcquisitionRunRecord,
    AttemptOutcome,
    CursorRecord,
    CursorState,
    DiscoveryRecord,
    IngestionPageRecord,
    IngestionRunRecord,
    PageOutcome,
    ProcessingStatus,
    RunOutcome,
    SourceKind,
    TranscriptRecord,
    TranscriptSegmentRecord,
    TranscriptWriteResult,
    UserRecord,
    VideoDetailRecord,
    VideoPartRecord,
    VideoRecord,
    VideoTagRecord,
    validate_error_code,
)
from .workflow import AsrPolicy, AsrProfile, JobKind, JobStatus, WorkflowJob, WorkflowPlan, WorkflowRepository

__all__ = [
    "ALLOWED_ACQUISITION_KINDS",
    "ALLOWED_ACQUISITION_OUTCOMES",
    "ALLOWED_ATTEMPT_OUTCOMES",
    "ALLOWED_CAPTION_SOURCE_KINDS",
    "ALLOWED_CURSOR_STATES",
    "ALLOWED_LOCAL_TRANSCRIPT_SOURCE_KINDS",
    "ALLOWED_PAGE_OUTCOMES",
    "ALLOWED_PROCESSING_STATUS",
    "ALLOWED_RUN_OUTCOMES",
    "ALLOWED_SOURCE_KINDS",
    "AcquisitionKind",
    "AcquisitionOutcome",
    "AcquisitionRunRecord",
    "AttemptOutcome",
    "AsrPolicy",
    "AsrProfile",
    "CursorRecord",
    "CursorState",
    "DatabaseConnection",
    "DiscoveryRecord",
    "IngestionPageRecord",
    "IngestionRunRecord",
    "JobKind",
    "JobStatus",
    "MAX_TIMELINE_MS",
    "MetadataRepository",
    "PageOutcome",
    "ProcessingStatus",
    "RunOutcome",
    "SchemaContractError",
    "SourceKind",
    "TranscriptRecord",
    "TranscriptRepository",
    "TranscriptSegmentRecord",
    "TranscriptWriteResult",
    "UserRecord",
    "VideoDetailRecord",
    "VideoPartRecord",
    "VideoRecord",
    "VideoTagRecord",
    "WorkflowJob",
    "WorkflowPlan",
    "WorkflowRepository",
    "duration_to_ms",
    "initialize_schema",
    "normalize_page_index",
    "open_database",
    "require_subtitle_schema",
    "validate_error_code",
]
