"""Normalized SQLite storage for Bilibili metadata.

The package root is the single import surface: the repository, the record
models, and the bootstrap helpers are all re-exported here.
"""

from .database import (
    DatabaseConnection,
    MetadataRepository,
    SchemaContractError,
    TranscriptRepository,
    duration_to_ms,
    initialize_schema,
    normalize_page_index,
    open_database,
    require_subtitle_schema,
)
from .models import (
    ALLOWED_ACQUISITION_KINDS,
    ALLOWED_ACQUISITION_OUTCOMES,
    ALLOWED_ATTEMPT_OUTCOMES,
    ALLOWED_CAPTION_SOURCE_KINDS,
    ALLOWED_CURSOR_STATES,
    ALLOWED_PAGE_OUTCOMES,
    ALLOWED_PROCESSING_STATUS,
    ALLOWED_RUN_OUTCOMES,
    ALLOWED_SOURCE_KINDS,
    MAX_TIMELINE_MS,
    AcquisitionKind,
    AcquisitionOutcome,
    AcquisitionRunRecord,
    AttemptOutcome,
    CursorRecord,
    CursorState,
    DiscoveryRecord,
    IngestionPageRecord,
    IngestionRunRecord,
    PageOutcome,
    ProcessingStatus,
    RunOutcome,
    SourceKind,
    TranscriptRecord,
    TranscriptSegmentRecord,
    TranscriptWriteResult,
    UserRecord,
    VideoPartRecord,
    VideoRecord,
    VideoTagRecord,
    validate_error_code,
)

__all__ = [
    "ALLOWED_ACQUISITION_KINDS",
    "ALLOWED_ACQUISITION_OUTCOMES",
    "ALLOWED_ATTEMPT_OUTCOMES",
    "ALLOWED_CAPTION_SOURCE_KINDS",
    "ALLOWED_CURSOR_STATES",
    "ALLOWED_PAGE_OUTCOMES",
    "ALLOWED_PROCESSING_STATUS",
    "ALLOWED_RUN_OUTCOMES",
    "ALLOWED_SOURCE_KINDS",
    "AcquisitionKind",
    "AcquisitionOutcome",
    "AcquisitionRunRecord",
    "AttemptOutcome",
    "CursorRecord",
    "CursorState",
    "DatabaseConnection",
    "DiscoveryRecord",
    "IngestionPageRecord",
    "IngestionRunRecord",
    "MAX_TIMELINE_MS",
    "MetadataRepository",
    "PageOutcome",
    "ProcessingStatus",
    "RunOutcome",
    "SchemaContractError",
    "SourceKind",
    "TranscriptRecord",
    "TranscriptRepository",
    "TranscriptSegmentRecord",
    "TranscriptWriteResult",
    "UserRecord",
    "VideoPartRecord",
    "VideoRecord",
    "VideoTagRecord",
    "duration_to_ms",
    "initialize_schema",
    "normalize_page_index",
    "open_database",
    "require_subtitle_schema",
    "validate_error_code",
]
