"""Offline preservation baseline for the pre-multiplatform archive contract.

This is representative, not exhaustive. It does not cover active leases,
interrupted file writes, rejected reviews, every caption language, or large
archives. IDs and wall-clock audit fields generated by production builders are
captured after construction; callers compare the resulting baseline unchanged.
DDL is loaded from the fixed source contract, never today's schema initializer.
The population helpers currently use the v1 public writers; a future schema
change must retain version-specific fixture writers or materialize frozen rows.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
import hashlib
from importlib import resources
import json
from pathlib import Path
import sqlite3
from typing import Any

from bili_asr import archive
from bili_asr.editorial import EditorialConfig
from bili_asr.publication import (
    create_edition, edit_edition, publish_edition, review_edition, withdraw_release,
)
from bili_asr.storage import (
    AcquisitionRunRecord, MetadataRepository, TranscriptRepository,
    TranscriptSegmentRecord, VideoTagRecord,
)
from bili_asr.storage.workflow import AsrPolicy, AsrProfile, JobKind, WorkflowRepository
from tests.fixtures.metadata_records import (
    make_cursor_record, make_discovery_record, make_page_record, make_part_record,
    make_run_record, make_user_record, make_video_record,
)
from tests.test_ai_editorial import FakeClient, runtime
from tests.test_publication import approve


@dataclass(frozen=True)
class MigrationArchive:
    archive_root: Path
    artifact_roots: tuple[Path, ...]
    ids: dict[str, Any]
    # Each row starts with the original SQLite rowid, including TEXT-PK tables.
    table_rows: dict[str, tuple[tuple[Any, ...], ...]]
    frozen_json: dict[str, str]
    files: dict[str, bytes]
    not_covered: tuple[str, ...] = (
        "active leases and interrupted writes", "rejected reviews",
        "all caption languages and acquisition failures", "large archive scale",
    )


def capture_table_rows(connection: sqlite3.Connection) -> dict[str, tuple[tuple[Any, ...], ...]]:
    """Capture every shipped table in insertion order without JSON rewriting."""
    tables = connection.execute(
        "SELECT name FROM sqlite_master WHERE type = 'table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    result = {}
    for row in tables:
        name = row[0]
        quoted = '"' + name.replace('"', '""') + '"'
        result[name] = tuple(tuple(value) for value in connection.execute(
            f"SELECT rowid, * FROM {quoted} ORDER BY rowid"
        ))
    return result


def _frozen_json(connection: sqlite3.Connection) -> dict[str, str]:
    result = {}
    for table in ("editorial_inputs", "editorial_revisions", "editorial_model_calls",
                  "editorial_chunk_results", "publication_editions", "workflow_jobs",
                  "workflow_attempts", "workflow_publications", "transcript_asr_evidence"):
        columns = [row[1] for row in connection.execute(f'PRAGMA table_info("{table}")')
                   if row[1].endswith("_json")]
        for row in connection.execute(f'SELECT rowid AS original_rowid, * FROM "{table}" ORDER BY rowid'):
            for column in columns:
                if row[column] is not None:
                    result[f"{table}:{row['original_rowid']}:{column}"] = row[column]
    return result


def _create_baseline_database(root: Path) -> sqlite3.Connection:
    root.mkdir(parents=True, exist_ok=True)
    contract = json.loads(resources.files("bili_asr.storage").joinpath(
        "migration-source-bilibili-v1.json"
    ).read_text(encoding="utf-8"))
    connection = sqlite3.connect(root / "archive.db")
    connection.row_factory = sqlite3.Row
    try:
        connection.execute("PRAGMA foreign_keys = ON")
        connection.execute("PRAGMA busy_timeout = 30000")
        for kind in ("table", "index", "view", "trigger"):
            for shape in contract["objects"].values():
                if shape["kind"] == kind:
                    connection.execute(shape["sql"])
        with connection:
            connection.execute("INSERT INTO manuscript_contract VALUES (1)")
        return connection
    except BaseException:
        connection.close()
        raise


def _run(repository: TranscriptRepository, run_id: str, kind: str, *, started_at: int = 200) -> None:
    repository.start_acquisition_run(AcquisitionRunRecord(
        run_id=run_id, kind=kind, selector_kind="pending", selector_target=None,
        requested_limit=None, credential_present=True, started_at=started_at,
    ))


def _transcripts(connection: sqlite3.Connection) -> dict[str, int]:
    repository = TranscriptRepository(connection)
    ids = {}
    for number, text in ((1, "最初的本地转录"), (2, "修订后的本地转录")):
        run_id = f"asr-version-{number}"
        _run(repository, run_id, "asr")
        written = repository.record_local_transcript(
            run_id=run_id, video_part_id=1, language="zh-CN",
            segments=(TranscriptSegmentRecord(0, 2400, text),),
            model_name="offline-model", model_revision="preservation-fixture",
            started_at=200, finished_at=210, created_at=220,
            coverage={"decoded_s": 3.0, "produced_s": 2.4, "coverage": 0.8,
                      "coverage_min": 0.9, "coverage_short": True},
            asr_evidence={"schema_version": 1, "fixture": "offline", "version": number},
        )
        repository.finish_acquisition_run(run_id, 230)
        ids[f"asr_v{number}"] = written.transcript_id
    for part, name, text in ((1, "reference", "平台字幕作为独立参照"),
                             (2, "draft_base", "未发布分 P 的字幕")):
        run_id = f"caption-{name}"
        _run(repository, run_id, "subtitle")
        written = repository.record_acquired_transcript(
            run_id=run_id, video_part_id=part, source_kind="subtitle-cc", language="zh-CN",
            segments=(TranscriptSegmentRecord(0, 2400, text),),
            started_at=200, finished_at=210, created_at=220,
        )
        repository.finish_acquisition_run(run_id, 230)
        ids[name] = written.transcript_id
    # Equal clocks and reverse lexical IDs exercise the rowid retry tie-break.
    for run_id, outcome, code, verified in (
        ("probe-z-first", "no-subtitle", None, True),
        ("probe-a-later", "failed", "rate_limited", False),
    ):
        _run(repository, run_id, "subtitle", started_at=300)
        repository.record_subtitle_attempt(
            run_id=run_id, video_part_id=3, outcome=outcome, error_code=code,
            started_at=300, finished_at=310, credential_verified=verified,
        )
        repository.finish_acquisition_run(run_id, 320)
    return ids


def _revision(connection: sqlite3.Connection, root: Path, base_id: int,
              reference_id: int | None, part_id: int) -> str:
    workflow, repository, _, executor = runtime(connection, root, FakeClient())
    prepared = repository.prepare(base_id, reference_id, EditorialConfig())
    proof_id, *_ = workflow.request_editorial(video_part_id=part_id, input_id=prepared["input_id"])
    result = executor.run()
    assert result.succeeded == 2 and result.failed == 0
    return repository.revision_for_job(proof_id)


def _publication_history(connection: sqlite3.Connection, roots: tuple[Path, ...],
                         revision: str) -> dict[str, str]:
    first = create_edition(connection, revision_id=revision, artifact_roots=roots, actor="fixture-editor")
    ids = {"edition_first": first["edition_id"]}
    previous = None
    edition = first
    for name, text in (("superseded", None), ("withdrawn", "第二版正文"),
                       ("current", "第三版正文")):
        if text is not None:
            edition = edit_edition(connection, edition_id=edition["edition_id"],
                                   markdown_text=text, actor="fixture-editor", note=name)
        approve(connection, edition)
        release = publish_edition(
            connection, edition_id=edition["edition_id"], artifact_roots=roots,
            write_root=roots[0], actor="fixture-publisher", expected_release_id=previous,
        )
        ids[f"release_{name}"] = release["release_id"]
        previous = release["release_id"]
        if name == "withdrawn":
            withdraw_release(connection, release_id=previous, actor="fixture-publisher", note="保留撤回历史")
            previous = None
    ids["edition_published"] = edition["edition_id"]
    newer = edit_edition(connection, edition_id=edition["edition_id"], markdown_text="尚待修改的新稿",
                         actor="fixture-editor", note="keep release and draft heads independent")
    review_edition(connection, edition_id=newer["edition_id"], status="in-review",
                   content_sha256=newer["content_sha256"], expected_status="pending-review", actor="fixture-reviewer")
    review_edition(connection, edition_id=newer["edition_id"], status="changes-requested",
                   content_sha256=newer["content_sha256"], expected_status="in-review",
                   actor="fixture-reviewer", note="需核对来源", issue_url="https://example.test/issues/278")
    ids["edition_current"] = newer["edition_id"]
    return ids


def build_migration_archive(archive_root: Path, artifact_root: Path | None = None) -> MigrationArchive:
    """Create a valid disposable archive; never accepts an existing database."""
    archive_root = Path(archive_root)
    if (archive_root / "archive.db").exists():
        raise ValueError("migration fixture requires a new archive")
    write_root = archive_root if artifact_root is None else Path(artifact_root)
    write_root.mkdir(parents=True, exist_ok=True)
    roots = tuple(dict.fromkeys((write_root, archive_root)))
    connection = _create_baseline_database(archive_root)
    try:
        metadata = MetadataRepository(connection)
        owner = make_user_record(display_name="采集作者")
        actual_uploader = replace(owner, mid=99, display_name="真实上传者")
        with metadata.transaction():
            metadata.upsert_user(owner)
            metadata.start_run(make_run_record("metadata-fixture"))
        metadata.record_page(
            make_page_record("metadata-fixture"), user=owner, additional_users=(actual_uploader,),
            videos=(make_video_record("BVpreserve", aid=1001),
                    replace(make_video_record("BVcancel", aid=1002), mid=99)),
            parts=(make_part_record("BVpreserve", cid=2011, processing_status="metadata_collected"),
                   make_part_record("BVpreserve", page_index=1, cid=2027, processing_status="metadata_collected"),
                   make_part_record("BVcancel", cid=2043, processing_status="metadata_collected")),
            discoveries=(make_discovery_record("BVpreserve", run_id="metadata-fixture"),
                         make_discovery_record("BVcancel", run_id="metadata-fixture", source_position=1)),
            cursor=make_cursor_record(state="limited", next_page=2),
            tags={"BVpreserve": (VideoTagRecord("BVpreserve", 1, "源标签", "old_channel"),),
                  "BVcancel": (VideoTagRecord("BVcancel", 2, "上次成功标签", "old_channel"),)},
            tag_observations={"BVpreserve": ("success_nonempty", None), "BVcancel": ("unavailable", "rate_limited")},
        )
        with metadata.transaction():
            metadata.finish_run(make_run_record("metadata-fixture", finished_at=120, outcome="limited"))
        ids = {"published_part": 1, "draft_part": 2, "cancelled_part": 3}
        ids.update(_transcripts(connection))
        revision = _revision(connection, write_root, ids["asr_v2"], ids["reference"], 1)
        draft_revision = _revision(connection, write_root, ids["draft_base"], None, 2)
        ids.update(revision=revision, draft_revision=draft_revision)
        ids.update(_publication_history(connection, roots, revision))
        draft = create_edition(connection, revision_id=draft_revision, artifact_roots=roots, actor="fixture-editor")
        ids["edition_unpublished"] = draft["edition_id"]

        audio_bytes = b"offline shared audio object; no media decoder required\n"
        audio_key = "audio/BVpreserve.p0.m4a"
        (write_root / "audio").mkdir(exist_ok=True)
        (write_root / audio_key).write_bytes(audio_bytes)
        audio_hash = hashlib.sha256(audio_bytes).hexdigest()
        with connection:
            connection.execute("INSERT INTO audio_objects VALUES (7, ?, ?, 'm4a', 3000, ?, 240)",
                               (audio_hash, len(audio_bytes), audio_key))
            connection.executemany("INSERT INTO part_audio_objects VALUES (?, 7, 240, 'workflow')", ((1,), (2,)))
        transcript = TranscriptRepository(connection).read_transcript(1, "asr-local", "zh-CN", version=2)
        bundle = archive.write_archive(write_root, {
            "bvid": "BVpreserve", "work_id": "BVpreserve:p0", "page_index": 0, "cid": 2011,
            "title": "保真样本", "duration_s": 3,
        }, [{"start": s.start_ms / 1000, "end": s.end_ms / 1000, "text": s.text}
            for s in transcript.segments], source="asr", asr_provenance={"model_name": "offline-model"})
        with connection:
            connection.execute("INSERT INTO workflow_publications VALUES (9, 1, ?, 250, ?)",
                               (ids["asr_v2"], json.dumps(bundle, ensure_ascii=False)))
        # Keep one file-only sidecar in the database root: the separate-root
        # variant must collect artifacts from both physical roots.
        (archive_root / "subtitles").mkdir(exist_ok=True)
        (archive_root / "subtitles/BVpreserve.p0.raw.json").write_text('{"fixture":"原始字幕证据"}\n', encoding="utf-8")

        workflow = WorkflowRepository(connection)
        profile = workflow.register_profile(AsrProfile("preservation", "offline-model", device="cpu"))
        workflow.plan(part_ids=[1, 3], policy=AsrPolicy.ALL, profile_id=profile)
        for kind in (JobKind.SUBTITLE, JobKind.AUDIO):
            while (job := workflow.claim("fixture-worker", kinds=(kind,))) is not None:
                if kind is JobKind.AUDIO and job.video_part_id == 3:
                    workflow.cancel(job_ids=[job.job_id])
                    ids["cancelled_job"] = job.job_id
                else:
                    result = {"outcome": "absent" if job.video_part_id == 3 else "stored"} if kind is JobKind.SUBTITLE else {
                        "storage_key": audio_key, "sha256": audio_hash, "duration_ms": 3000,
                    }
                    workflow.finish(job.job_id, worker_id="fixture-worker", result=result)
        ids["blocked_job"] = connection.execute(
            "SELECT job_id FROM workflow_jobs WHERE kind='asr' AND video_part_id=3"
        ).fetchone()[0]
        return MigrationArchive(
            archive_root=archive_root, artifact_roots=roots, ids=ids,
            table_rows=capture_table_rows(connection), frozen_json=_frozen_json(connection),
            files={path.relative_to(base).as_posix(): path.read_bytes()
                   for base in roots for directory in ("audio", "transcripts", "documents", "subtitles", "publications")
                   for path in (base / directory).rglob("*") if path.is_file()},
        )
    finally:
        connection.close()
